---
- name: download key for Ceph repo
  get_url:
    url: https://download.ceph.com/keys/release.asc
    dest: /etc/apt/trusted.gpg.d/ceph.asc

- name: Add ceph repository
  apt_repository:
    repo: "deb https://download.ceph.com/debian-{{ ceph_version }}/ {{ ansible_distribution_release }} main"
    state: present
    filename: ceph
  register: ceph_repo

- name: install ceph from packages
  apt:
    update_cache: "{{ ceph_repo is changed }}"
    name: ceph-mds
    state: present

- name: fix rights
  file:
    path: /etc/ceph
    state: directory
    owner: ceph
    group: ceph

- name: check if needed conf files are present
  stat:
    path: "/tmp/{{ item|basename }}"
  register: st_conf_files
  delegate_to: localhost
  become: false
  loop:
    - /etc/ceph/ceph.conf
    - /etc/ceph/ceph.client.admin.keyring

- name: copy files to all the nodes
  copy:
    src: "/tmp/{{ item.item|basename }}"
    dest: "{{ item.item }}"
    owner: ceph
    group: ceph
  when: item.stat.exists
  loop: "{{ st_conf_files.results }}"

- name: create mds directory
  file:
    path: "/var/lib/ceph/mds/ceph-{{ inventory_hostname }}"
    state: directory
    owner: ceph
    group: ceph
    recurse: true

- name: create mds keyring
  command: "ceph-authtool --create-keyring /var/lib/ceph/mds/ceph-{{ inventory_hostname }}/keyring --gen-key -n mds.{{ inventory_hostname }}"
  become_user: ceph
  become: true
  args:
    creates: "/var/lib/ceph/mds/ceph-{{ inventory_hostname }}/keyring"

- name: check if mds user exists
  command: "ceph auth get mds.{{ inventory_hostname }}"
  become_user: ceph
  become: true
  failed_when: false
  changed_when: false
  register: mds_user

- name: create user for mds service
  command: "ceph auth add mds.{{ inventory_hostname }} osd 'allow rwx' mds 'allow' mon 'allow profile mds' -i /var/lib/ceph/mds/ceph-{{ inventory_hostname }}/keyring"
  become_user: ceph
  become: true
  when: mds_user.rc != 0

- name: start mds daemon
  systemd:
    name: "ceph-mds@{{ inventory_hostname }}"
    enabled: true
    state: started
